export const DOCTORS_DATA = [
  {
    _id: 'doc1',
    name: 'Dr. Suresh Mahatme',
    specialization: 'Cataract & Refractive Surgery',
    experience: 22,
    qualification: 'MS (Ophthalmology), FICO (London)',
    availability: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    timings: '9:00 AM – 1:00 PM',
    bio: 'Pioneer in phacoemulsification and bladeless LASIK with over 15,000 successful cataract surgeries.',
    image: null,
    color: 'teal',
    rating: 4.9,
    reviews: 312,
  },
  {
    _id: 'doc2',
    name: 'Dr. Priya Mahatme',
    specialization: 'Retina & Vitreous',
    experience: 17,
    qualification: 'DNB (Ophthalmology), Fellowship Retina – LVPEI',
    availability: ['Mon', 'Wed', 'Fri', 'Sat'],
    timings: '10:00 AM – 2:00 PM',
    bio: 'Expert in diabetic retinopathy, macular degeneration, and intravitreal injections using cutting-edge OCT guided therapy.',
    image: null,
    color: 'blue',
    rating: 4.8,
    reviews: 247,
  },
  {
    _id: 'doc3',
    name: 'Dr. Anil Deshmukh',
    specialization: 'Glaucoma & Cornea',
    experience: 14,
    qualification: 'MS (Ophthalmology), Fellowship Cornea – Aravind',
    availability: ['Tue', 'Thu', 'Sat'],
    timings: '11:00 AM – 3:00 PM',
    bio: 'Specializes in advanced glaucoma management, keratoconus treatment (C3R/ICL), and corneal transplantation.',
    image: null,
    color: 'purple',
    rating: 4.7,
    reviews: 189,
  },
  {
    _id: 'doc4',
    name: 'Dr. Kavita Joshi',
    specialization: 'Pediatric Ophthalmology',
    experience: 11,
    qualification: 'MS (Ophthalmology), Fellowship Pediatric Eye – NIMHANS',
    availability: ['Mon', 'Tue', 'Wed', 'Thu'],
    timings: '9:00 AM – 12:00 PM',
    bio: 'Dedicated to children\'s eye care — squint surgery, amblyopia therapy, and childhood vision screenings.',
    image: null,
    color: 'green',
    rating: 4.9,
    reviews: 156,
  },
  {
    _id: 'doc5',
    name: 'Dr. Rajesh Kulkarni',
    specialization: 'Oculoplasty & Orbit',
    experience: 16,
    qualification: 'MS (Ophthalmology), FRCS (Glasgow)',
    availability: ['Wed', 'Thu', 'Fri', 'Sat'],
    timings: '2:00 PM – 6:00 PM',
    bio: 'Expert in eyelid surgeries, orbital tumors, DCR procedures, and cosmetic eye reconstructions.',
    image: null,
    color: 'orange',
    rating: 4.8,
    reviews: 203,
  },
  {
    _id: 'doc6',
    name: 'Dr. Sneha Raut',
    specialization: 'Low Vision & Neuro-Ophthalmology',
    experience: 9,
    qualification: 'MD (Ophthalmology), Fellowship Neuro-Ophth – AIIMS',
    availability: ['Tue', 'Fri', 'Sat'],
    timings: '10:00 AM – 1:00 PM',
    bio: 'Specializes in vision rehabilitation, optic nerve disorders, double vision, and visual field defects.',
    image: null,
    color: 'rose',
    rating: 4.7,
    reviews: 124,
  },
]

export const COLOR_MAP = {
  teal:   { bg: 'bg-teal-50 dark:bg-teal-950/30',   ring: 'ring-teal-500',   badge: 'bg-teal-100 text-teal-700 dark:bg-teal-900/50 dark:text-teal-300',   avatar: 'from-teal-500 to-teal-700' },
  blue:   { bg: 'bg-blue-50 dark:bg-blue-950/30',   ring: 'ring-blue-500',   badge: 'bg-blue-100 text-blue-700 dark:bg-blue-900/50 dark:text-blue-300',   avatar: 'from-blue-500 to-blue-700' },
  purple: { bg: 'bg-purple-50 dark:bg-purple-950/30', ring: 'ring-purple-500', badge: 'bg-purple-100 text-purple-700 dark:bg-purple-900/50 dark:text-purple-300', avatar: 'from-purple-500 to-purple-700' },
  green:  { bg: 'bg-green-50 dark:bg-green-950/30',  ring: 'ring-green-500',  badge: 'bg-green-100 text-green-700 dark:bg-green-900/50 dark:text-green-300',  avatar: 'from-green-500 to-green-700' },
  orange: { bg: 'bg-orange-50 dark:bg-orange-950/30', ring: 'ring-orange-500', badge: 'bg-orange-100 text-orange-700 dark:bg-orange-900/50 dark:text-orange-300', avatar: 'from-orange-500 to-orange-700' },
  rose:   { bg: 'bg-rose-50 dark:bg-rose-950/30',   ring: 'ring-rose-500',   badge: 'bg-rose-100 text-rose-700 dark:bg-rose-900/50 dark:text-rose-300',   avatar: 'from-rose-500 to-rose-700' },
}

export const TIME_SLOTS = [
  '09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM',
  '11:00 AM', '11:30 AM', '12:00 PM', '12:30 PM',
  '02:00 PM', '02:30 PM', '03:00 PM', '03:30 PM',
  '04:00 PM', '04:30 PM', '05:00 PM', '05:30 PM',
]
